# Generated by Django 2.2.3 on 2019-07-14 23:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=30)),
                ('publish_on', models.DateTimeField(verbose_name=datetime.datetime(2019, 7, 14, 23, 10, 6, 448114, tzinfo=utc))),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
