# Generated by Django 2.2.3 on 2019-07-14 23:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 14, 23, 19, 42, 414890, tzinfo=utc)),
        ),
    ]
