# Generated by Django 2.2.3 on 2019-07-15 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks_app', '0003_auto_20190715_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='about',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='picture',
            field=models.ImageField(default=' ', upload_to='book_pics'),
            preserve_default=False,
        ),
    ]
